### ISSUE TITLE
# Método suma

### ISSUE THREAD

**Issue by vargasjuanj** [vargasjuanj/Calculadora#20]
[Implementación](https://github.com/vargasjuanj/Calculadora/wiki#ejemplo-a-usar)

**Comment by marcelocattani** [comment]
Ya termine mi parte. Me lo asigne para alivianar un poco lo que llevas haciendo @vargasjuanj, se que esto ya lo tenes mas que claro.

**Comment by cortezalberto** [comment]
Còmo va ese aprendizaje de trabajar en grupo???

**Comment by marcelocattani** [comment]
@cortezalberto  Excelente vamos avanzando. Hemos tenido algun que otro error, pero esta siendo una muy buena practica.

**Comment by cortezalberto** [comment]
Creanmè que esta pràctica pequeña les va a ayudar mucho para hacer los
trabajos con el Profe Magni y conmigo!

**Comment by marcelocattani** [comment]
Estamos seguros de eso. Le agradecemos su apoyo.

**Comment by cortezalberto** [comment]
Alguien sabe como bajar cursos de Udemy comprados??

**Comment by vargasjuanj** [comment]
Dale Marcelo gracias, si mejor que ya lo hayas hecho vos.
Profe como le va? gracias por la dedicación que le pone para guiarnos bien!!
...Creo que latuca sabe, pregunte en el grupo de whatsapp
